AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bose Predictive Maintenance System'

Parameters:
  HealthMetricsTableName:
    Type: String
    Description: Name of the DynamoDB table for storing Bose device health metrics

  MaintenanceAlertTopicName:
    Type: String
    Description: Name of the SNS topic for sending maintenance alerts

  LambdaCodeS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda function code

  LambdaCodeS3Key:
    Type: String
    Description: S3 key for the Lambda function code

  HealthDataBucketArn:
    Type: String
    Description: ARN of the S3 bucket for ingesting Bose device health data

Resources:
  BoseHealthMetricsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref HealthMetricsTableName
      AttributeDefinitions:
        - AttributeName: productId
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: productId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  MaintenanceAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref MaintenanceAlertTopicName

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MaintenanceAlertTopic
      Endpoint: hu.shuo@northeastern.edu
      Protocol: email

  HealthDataProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-health-data-processor'
      Handler: index.handler
      Role: !GetAtt HealthDataProcessorRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref LambdaCodeS3Key
      Runtime: python3.10
      Timeout: 120
      Environment:
        Variables:
          HEALTH_METRICS_TABLE: !Ref BoseHealthMetricsTable
          ALERT_TOPIC_ARN: !Ref MaintenanceAlertTopic
          HEALTH_DATA_BUCKET: !Ref HealthDataBucketArn

  HealthDataProcessorPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HealthDataProcessorFunction
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceArn: !Ref HealthDataBucketArn

  HealthDataProcessorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: HealthDataAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub '${HealthDataBucketArn}/*'
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:BatchWriteItem
                Resource: !GetAtt BoseHealthMetricsTable.Arn
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref MaintenanceAlertTopic

Outputs:
  HealthMetricsTableName:
    Description: Name of the DynamoDB table for Bose device health metrics
    Value: !Ref BoseHealthMetricsTable

  MaintenanceAlertTopicArn:
    Description: ARN of the SNS topic for Bose device maintenance alerts
    Value: !Ref MaintenanceAlertTopic

  HealthDataProcessorFunctionArn:
    Description: ARN of the Lambda function for processing Bose health data
    Value: !GetAtt HealthDataProcessorFunction.Arn
